### ISSUE TITLE
use styled-components for styling?

### ISSUE THREAD

**Issue by xkawi** [xkawi/react-universal-saga-modular#4]
have anyone checked [styled-components](https://github.com/styled-components/styled-components)?

The main benefit is that we can remove the styling portion (css, less, scss) at webpack config and remove bootstrap all together. Hence, reducers the bundle size.

what do you guys think? I want to gauge the overall interest about this move before actually implementing it.

**Comment by leandrooriente** [comment]
Hi @xkawi 

I'm fighting to integrate css-modules to the project. 

You think that styled-components is a better approach?

**Comment by xkawi** [comment]
@leandrooriente have a look at this article to have some idea why styled-components is a better/preferred approach: [💅 styled components 💅 — Production Patterns](https://medium.com/@jamiedixon/styled-components-production-patterns-c22e24b1d896)

**Comment by xkawi** [comment]
closing this for now, as I have no time to work on it.
